"""Automated GitHub Pull Request bot creating remediation PRs."""

import base64
import time
from typing import Any, Dict, Optional
import requests

from packages.core.fixer.engine import FixerEngine


class GitHubPRBot:
    """Automates creation of remediation Pull Requests on customer GitHub repositories."""

    def __init__(self, github_token: str, base_api_url: str = "https://api.github.com"):
        self.token = github_token.strip()
        self.base_url = base_api_url.rstrip("/")
        self.headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json",
        }
        self.fixer = FixerEngine()

    def create_remediation_pr(
        self,
        repo: str,
        site_url: str,
        base_branch: str = "main",
        custom_fixes: Optional[Dict[str, str]] = None,
    ) -> Dict[str, Any]:
        """Generate and commit fixes directly into a new pull request on repo."""
        fixes = custom_fixes or self.fixer.generate_all_fixes(site_url)
        branch_name = f"agentready/remediation-{int(time.time())}"

        # 1. Get base branch commit SHA
        ref_resp = requests.get(f"{self.base_url}/repos/{repo}/git/ref/heads/{base_branch}", headers=self.headers, timeout=10.0)
        if ref_resp.status_code != 200:
            return {"success": False, "error": f"Failed to get base branch '{base_branch}': {ref_resp.text}"}

        base_sha = ref_resp.json()["object"]["sha"]

        # 2. Create new branch
        create_branch_resp = requests.post(
            f"{self.base_url}/repos/{repo}/git/refs",
            json={"ref": f"refs/heads/{branch_name}", "sha": base_sha},
            headers=self.headers,
            timeout=10.0,
        )
        if create_branch_resp.status_code not in [200, 201]:
            return {"success": False, "error": f"Failed to create branch '{branch_name}': {create_branch_resp.text}"}

        # 3. Commit files
        committed_files = []
        for filename, content in fixes.items():
            encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")
            commit_payload = {
                "message": f"feat(agentready): add AI agent-ready {filename}",
                "content": encoded,
                "branch": branch_name,
            }
            file_resp = requests.put(f"{self.base_url}/repos/{repo}/contents/{filename}", json=commit_payload, headers=self.headers, timeout=10.0)
            if file_resp.status_code in [200, 201]:
                committed_files.append(filename)

        # 4. Open Pull Request
        pr_body = (
            f"## 🤖 AgentReady Automated Remediation Bundle\n\n"
            f"This PR was generated automatically by **AgentReady** to optimize `{site_url}` for AI search engines and autonomous agents.\n\n"
            f"### 📦 Changes Included:\n"
            f"- **`/llms.txt`**: Standardized Markdown context for LLMs\n"
            f"- **`robots.txt`**: Explicit crawler permissions for `GPTBot`, `ClaudeBot`, `PerplexityBot`, `Google-Extended`\n"
            f"- **`schema-ld.json`**: Schema.org structured data starter template\n\n"
            f"---\n*Generated by [AgentReady](https://github.com/daryllrebeiro/agent-ready-kit)*"
        )

        pr_resp = requests.post(
            f"{self.base_url}/repos/{repo}/pulls",
            json={
                "title": "feat(ai-readiness): add AgentReady llms.txt and crawler permissions",
                "head": branch_name,
                "base": base_branch,
                "body": pr_body,
            },
            headers=self.headers,
            timeout=10.0,
        )

        if pr_resp.status_code in [200, 201]:
            pr_data = pr_resp.json()
            return {
                "success": True,
                "pr_url": pr_data.get("html_url"),
                "pr_number": pr_data.get("number"),
                "branch": branch_name,
                "committed_files": committed_files,
            }

        return {"success": False, "error": f"Failed to create PR: {pr_resp.text}"}
